name: bark_dart
description: bark_dart library for make your program dart more easy.
version: 0.0.0
repository: https://github.com/azkadev/azkadev.git
issue_tracker: https://github.com/azkadev/azkadev.git
homepage: https://youtube.com/@azkadev


executables:
  bark_dart: bark_dart
  

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.0.2
  galaxeus_lib: ^0.0.75
  path: ^1.8.3
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  msix: ^3.15.1
  packagex: ^0.0.28
  test: ^1.24.4

msix_config: 
  display_name: bark_dart
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.bark_dart
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam

packagex:
  name: bark_dart
  dart_target: bark_dart
  flutter_target: main
  dart_name: bark_dart
  flutter_name: bark_dart
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  
